services:
- docker
install: make build
stages:
- name: echo
- name: publish
  if: branch = master AND type != pull_request
jobs:
  include:
  - stage: echo
    script: echo
  - stage: publish
    name: Publish production image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish
env:
  global:
  - secure: zUUGeP5b2yNKFYFapmpd+z38i24FIQAQxgpx2dytk6az2LvO55Zlvd+PJcdeCczL+Xk3B9FLUhaRXg3jS7X0qEBCxL8YdM/xwklUgZXbhri8xk4z+4UDlCiqAzsq7T6J8t6+vv3v1SHqYhgm/qQRzcSThof5L14ll944dpou2JAMT/hZClyBRslutHNQOVgqfmB8zDVRXeQBD8AevPCvUnZ+2nFRNAhb3y3Hlyse5q7yLkjFc7K15kOJ3qameAh5up6eOFAiyIRHbT5s1e2DpRDDyQrlms3ahGeo2C3y07j9lrIJ6fZotxJF0+q/ozELZnwkNCo66z/wvB/L+Qt/L2YYH1DFb0qO94H3E35TIc7TBFeQ2Pw0VPJnbMlPb1zvI0w8tOHBNeVtPZQl65iZT9dJE34fJcuLL40f8Sjcb1OkrKN4XZbrzX40tZXqNeyvNKCexeRjq7/VmIsVZcNj2S/L8CEp6YR9wZ7cpm8mUfmMILHoeUevPSemEc/P1fgCaMHgZKAMsGKNNTyGbyMLMMkwMEMd/MPwSw9/oL3Z7s3u5MnqKEfk35Hed0zjr1b/o/6uF3bxFeG+D8FtoBdzO6VLa6YsTjQo9kaPc7nh8MgZDoY+zfZ3QEbPn9qj5/tCGsHT8Uxe1+Yj4WlU+jFPC0804FZoUwHOEhBgRyy81Do=
  - secure: dDPu5ej8aa+tKNjSMzB8CfSk5tEvcfzZ7r+wpDzE1YhbPrjwrLGnuJI27kZUrFnWOZv2Y9Fwugs6+xMmxl88syxS2VlZxfiQ4Tex8zp5C12qVR8JdUtgA0oG2I7oXQARs5t7QhW3nWHRti8DdDToIltv0coGV45eDlwA3xtSTt6fxG9nmexEUNytPCl9End4Kbf37yb/DUFpqNdyiEw5s2FxIQ/VV4XFJg3/R3/ABkhv/1v/0TeXO4bUr1nnXT07fj1Qq1GmRSKWbHeF6GMUwVHU4CRmHYuHO2BD7EXtS63pUXaN/NX4H/Cw8bMXzPE6FemSQEj8/M36JwktmdfX1z5ff4pwHkE3TpzDORw2D/mknR1y2IYthttKB3NNIz/GSw1lWosSSRkqz2DKKWGho5lNa4lla0KC0TOWVsKQhD19PLMRdozI9qEfOP1wL7cG6JxtaAHsztQqUiXUyZ0GNcYqmaPAe/w1WVjFpfbUf9T3xCjlu9IQU7VgaWWiQQC++I2hAYaDPfaHIuBNaCzwdJLklge9Nr1FOuea8k+xPXK3FddPdXKbSpe9BUNvL7LrqaQZUKtzPGLSwTUooKni4hkYCGup5acjPrFtYPcMRV0PmozEkhN24lhBAwdLMvZCKU/RqDkIZmLFHLO8GhtNiJG2hsVm4W7T5Ag38Ljz1zA=
