ARG REPOSITORY=docker.osdc.io
ARG BUILDER_TAG=3.1.0

### Download tarball to scratch layer
FROM scratch AS src
ARG VERSION
ADD https://github.com/broadinstitute/gatk/releases/download/${VERSION}/gatk-${VERSION}.tar.gz gatk.tar.gz

FROM ${REPOSITORY}/ncigdc/amzn2023-builder:${BUILDER_TAG} AS builder

ARG VERSION

### Mount tarball from scratch layer and untar into builder layer
RUN --mount=from=src,target=/src <<EOF
mkdir -p /gatk
tar -oxzf /src/gatk.tar.gz -C /gatk
EOF

# Example add package step
RUN dnf install -y \ <<EOF
    build-essential \
    openjdk-8-jre-headless\
    r-base \
    unzip
EOF
# RUN dnf install -y tools

### Run install steps
WORKDIR /gatk

RUN <<EOF
mv gatk-${VERSION}/* /usr/local/bin/
rm -rf gatk-*
ln -s /usr/local/bin/gatk-package-${VERSION}-local.jar /usr/local/bin/gatk.jar
EOF

### Multi-stage build:
#FROM ${REPOSITORY}/ncigdc/amzn2023:${BUILDER_TAG}

#COPY --from=builder /usr/local /usr/local

ENTRYPOINT ["java", "-jar", "/usr/local/bin/gatk.jar"]
